baseURL = "https://eventogae.netlify.app/"
languageCode = "pt-br"
title = "Evento GAE"
theme = "hugo-arcana"
copyright = " Powered by @joaokropf"

[params]
    description = ""
    show_post_dates = false
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/UNIRIOGAE"
    [[params.social]]
        title = "Github"
        icon = "fa-github"
        url = "http://gae.uniriotec.br/"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/gae_assessoria/"     