baseURL = "eventogae.netlify.app"
languageCode = "en-us"
title = "Evento GAE"
theme = "hugo-arcana"
copyright = "© Powered by @joaokropf"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/UNIRIOGAE"
    [[params.social]]
        title = "Github"
        icon = "fa-github"
        url = "http://gae.uniriotec.br/"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/gae_assessoria/"     